services:

  yourls:
    image: yourls:latest
    container_name: yourls
    restart: unless-stopped
    ports:
      - 8080:80
    expose:
      - 80
    env_file:
      - .env
    volumes:
      - ./security.conf:/etc/apache2/conf-enabled/security.conf:ro      
    #networks:
    #  - proxy
    #labels:
    #  - traefik.enable=true
    #  - traefik.http.routers.yourls.rule=Host(`s.ptf.one`)
    #  - traefik.http.services.yourls.loadbalancer.server.port=80
    #  - traefik.docker.network=proxy
    #  # Part for optional traefik middlewares
    #  - traefik.http.routers.CHANGEME.middlewares=local-ipwhitelist@file,authelia@docker     

  mysql:
    image: mysql:latest
    container_name: yourls-db
    restart: unless-stopped
    expose:
      - 3306
    env_file:
      - .env
    volumes:
      - ./yourls_db:/var/lib/mysql
    #networks:
    #  - proxy

#networks:
#  proxy:
#    external: true